FROM python:3.10.4-slim-buster
WORKDIR tests/functional

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV ENV=dev

RUN pip install --upgrade pip  --no-cache-dir
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY tests/../.. .
CMD pytest -s -vv
